import Head from "next/head";
import LazyImage from "./Fox";
import { MouseEventHandler, useState } from "react";

// function random para generar img aleatorio
//función explicita que devuelve un numero
const numberRandom = (): number => Math.floor(Math.random() * 123) + 1;

//función explicita de generar id único
const generateId = (): string =>
  Math.random().toString(36).substr(2, 9) + "_" + Date.now();

//explicito objeto
type Images = {
  id: string;
  url: string;
};

export default function Home() {
  const [images, setImages] = useState<Array<Images>>([]);

  const addImage: MouseEventHandler<HTMLButtonElement> = (event) => {
    event.preventDefault();
    const target = event.target;
    const newImage: Images = {
      id: generateId(),
      url: `https://randomfox.ca/images/${numberRandom()}.jpg`,
    };
    setImages([...images, newImage]);
  };

  return (
    <>
      <Head>
        <title>React Typescript</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="p-8 text-3xl font-bold underline underline-offset-8 text-center">
          Imágenes de Zorros
        </h1>
        <div className="w-full text-center mb-2">
          <button
            onClick={addImage}
            className="rounded px-8 py-2 bg-slate-500 text-white hover:bg-slate-600"
          >
            Agregar Imagen
          </button>
        </div>
        {images.map(({ id, url }, index) => (
          <div key={id} className="p-2">
            <LazyImage
              src={url}
              onLazyLoad={(img) =>
                console.log(
                  `la imagen ${index + 1} se ha cargado, valor de la imagen: `,
                  img
                )
              }
              onClick={() => console.log("se hizo click en la image")}
              alt={`imagen ${id}`}
              title="Imagen de zorros"
            />
          </div>
        ))}
      </main>
    </>
  );
}
